### ISSUE TITLE
Is breve accent in various Greek words intentional?

### ISSUE THREAD

**Issue by ArmorBearer** [helmadik/LSJLogeion#3]
I have seen a Unicode breve accent character in some places, and I wondered if this is a typo or if combining breve accent was intended or...?  Is this something that needs to be corrected?

Here are some examples:

\<cit\>\<quote lang="greek"\>ἄτε˘κνος\</quote\>\<author\>A.\</author\>\</cit\>
\<headword extent="suff" lang="greek" opt="n" orth_orig="αὐλά˘κ-ιον"\>αὐλάκιον\</headword\>
\<itype lang="greek" opt="n"\>δη˘ῐων\</itype\>
\<pron extent="full" lang="greek" opt="n"\>[ω˘]\</pron\>
\<foreign lang="greek"\>ἥρω˘ος\</foreign\>

Looks like there are 60 occurrences...

**Comment by helmadik** [comment]
Oh, good point! I think it may originally have been entered this way because not all fonts readily render an omega or an epsilon with a breve (because omegas ought to be always long, and epsilons always short) -- or we might have produced that in the course of converting to unicode because there isn't a precombined character available.. Lost in history I'm afraid. But you're right; it should be repaired.
ETA: They were also used when the character already has a different diacritic. I've folded them in now with combining breve, and we'll see what happens when we try to display it:-) Finally, a handful of the 60 were describing certain metrical patterns. Those replaced with metrical breve.

**Comment by ArmorBearer** [comment]
Thanks, @helmadik, for the clarification and the repair!
