### ISSUE TITLE
Missing sense numbers in XML text

### ISSUE THREAD

**Issue by ArmorBearer** [helmadik/LSJLogeion#7]
The sense number for each entry is in an attribute, rather than in the text, so it is removed when the XML elements are removed, as is normally done when XML data is formatted for display.

We have had to address this through the use of CSS, which I show here for the benefit of others:

```
sense:before {
    content: attr(n) '. ';
}
```

This copies the sense number from the element attribute to the element text before the element tags are removed.

**Comment by helmadik** [comment]
I've added some undifferentiated `<sense>` tags where there was none, in order to add more structure to an otherwise unstructured entry, for instance when a derivative is introduced as " hence, _X_". I don't want to break up the entry for these, but I do want them to stand out typographically. 
Also, where Perseus added an "A" meaning without there being one in the print edition, I've removed the attribute. If you see  a level 1 sense with an n="", that is a Perseus A. 

Example of both:
`<div2 id="crossa)ggeiologe/w" orig_id="n386" key="a)ggeiologe/w" type="main" opt="n"><head extent="full" lang="greek" opt="n" orth_orig="ἀγγειο-λογέω">ἀγγειολογέω</head>, <sense id="n386.0" n="" level="1" opt="n"><i>take up a vein and operate upon it,</i> c. acc., interp. in <bibl n="Perseus:abo:tlg,0565,001:1:85" default="NO"><author>Sor.</author> 1.85</bibl>, cf. <bibl n="Perseus:abo:tlg,0715,001:6:5" default="NO"><author>Paul.Aeg.</author> 6.5</bibl></sense><sense>:—hence <pos opt="n">Subst.</pos> <orth extent="suff" lang="greek" opt="n">ἀγγειο-λογία</orth>, <gen lang="greek" opt="n">ἡ</gen>, <author>Antyll.</author> or <author>Heliod.</author> ap. <bibl n="Perseus:abo:tlg,0722,001:45:18:32" default="NO"><author>Orib.</author> 45.18.32</bibl>,  <bibl n="Perseus:abo:tlg,0718,007:95" default="NO"><author>Aët.</author> 7.95</bibl>.</sense></div2>`

**Comment by ArmorBearer** [comment]
> Also, where Perseus added an "A" meaning without there being one in the print edition, I've removed the attribute. If you see a level 1 sense with an n="", that is a Perseus A.

I think I will put them back in my local copy, since, without them my CSS solution is broken, and I see, e.g.:
![image](https://user-images.githubusercontent.com/48448683/121088734-ce55da00-c7ab-11eb-86eb-055bd46cf3b1.png)
*(Note the period before the (B) and (C) items.)

Since there are 3 senses in this entry, I think they should probably not have n="".  Fortunately, this seems to be the only occurrence of 2 n="" attributes in a single entry, so I can fix that relatively easily by hand.  (Just wish I wouldn't need to do that every time we get an update to the LSJ from y'all.)

Oddly, in both the Perseus online dictionary and the Kindle version, these latter 2 senses have been split off as separate entries, even though the sense 'number' has been shown explicitly in the text rather than in the 'n' attribute.  Not sure why... perhaps because the sense has been given its own headword?  (A very strange way to do things, to my linguist mind.)

**Comment by helmadik** [comment]
The three words are really differently derived:
an with short alpha, the modal particle.
an with long alpha, also hn depending on dialect. That same modal particle
merged with the conditional conjunction ei.
an as variant form of ana (prep/adverb).
(and these are just part of the total set of possibilities).

LSJ style is to use (B) (C) for homonyms. from the fact that the orig_id-s
are not continuous, I would conclude that I merged the articles, probably
(I have no recollection) because our original
database presentation (in PhiloLogic) would by default show one entry at a
time, and I wanted to make sure all ἄν entries would be visible at the same
time.


Helma Dik
Department of Classics
University of Chicago

**Comment by helmadik** [comment]
PS - the awkwardness of the automatic A is shown at the very start of the
an entry..
[image: image.png]
We've now changed this to look more like the print edition, while retaining
the `<sense..>` tag where it was.

Helma Dik
Department of Classics
University of Chicago
